insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (1,'AA','Super Admin','超级管理员',true,true,'1');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (2,'I','Investor','投资人',true,false,'116,121');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (3,'BR','Broker','经纪人',true,false,'140,150');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (4,'B','Borrower','融资人',true,false,'124');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (5,'SP','Sponsor','保荐人',true,false,'');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (6,'AG','Agency','营销机构',true,false,'160,170');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (7,'G','Guarantee','担保机构',true,false,'130,210');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (8,'IE','Investment Enterprise','投资机构',true,false,'');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (9,'SE','Sponsor Enterprise','保荐机构',true,false,'');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (10,'O','Operator','操作员',true,false,'130');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (11,'NO','Normal Operator','普通运营账户',false,true,'');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (12,'AO','Audit Operator','运营审核账户',false,true,'64');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (13,'A','Admin','管理员',false,true,'1');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (14,'P','Platform','平台分润角色',true,false,'');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (15,'L','Guarantee xd','小贷机构',true,false,'130,210');
insert into role (id,name,name_en,name_zh,is_front_role,is_admin_role,permission_ids) values (16,'S','Super Broker','超级经纪人',true,false,'140,150,160,170');
